# Generated by Django 3.0 on 2020-11-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('websiteName', models.CharField(max_length=20)),
            ],
        ),
    ]
