# Generated by Django 3.0 on 2020-11-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0002_websitesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modified_time',
            new_name='modifiedTime',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
