# Generated by Django 3.0 on 2020-11-14 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0004_auto_20201113_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesettings',
            name='websiteUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='migration.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
