# Generated by Django 3.0 on 2020-11-15 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0006_auto_20201114_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='migration.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='migration.Tag'),
            preserve_default=False,
        ),
    ]
