# Generated by Django 3.0 on 2020-11-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migration', '0007_auto_20201115_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.AddField(
            model_name='category',
            name='owner',
            field=models.ManyToManyField(to='migration.User'),
        ),
        migrations.AddField(
            model_name='tag',
            name='owner',
            field=models.ManyToManyField(to='migration.User'),
        ),
    ]
